"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "./vendor/xlsx-runtime";

type Event={id:string;name:string;label:string;date:string;venue:string;city?:string;opened:string;capacity:number;status:string;lifecycle?:"active"|"paused"|"archived"};
type Client={id:string;name:string;phone:string;email:string;cpf:string;birth:string;city:string};
type Sale={id:string;clientId:string;eventId:string;at:string;qty:number;value:number;ticketType?:string;importId?:string;sourceKey?:string};
type ImportHistory={id:string;eventId:string;fileName:string;importedAt:string;total:number;valid:number;added:number;duplicates:number;errors:number;status:"Concluída"|"Desfeita"|"Removida";saleIds:string[];createdClientIds:string[];errorRows:{row:number;reason:string}[]};
type Store={events:Event[];clients:Client[];sales:Sale[];imports:ImportHistory[]};
type FieldKey="ignore"|"name"|"cpf"|"phone"|"email"|"birth"|"city"|"date"|"time"|"qty"|"value"|"ticketType"|"saleId";
type PendingImport={fileName:string;format:"CSV"|"XLSX";sheetName:string;headerRow:number;headers:string[];rows:string[][];mapping:FieldKey[]};

const EVENTS:Event[]=[
 {id:"oboe26",name:"OBOÉ 3 ANOS",label:"OBOÉ",date:"2026-10-10T22:00:00",venue:"Armazém Convention",opened:"2026-08-20T12:00:00",capacity:2400,status:"Vendas acelerando"},
 {id:"ginga26",name:"GINGA — Primavera",label:"GINGA",date:"2026-09-19T21:00:00",venue:"Trapiche Barnabé",opened:"2026-08-12T18:00:00",capacity:1800,status:"Perto de sold out"},
 {id:"retro26",name:"RETRONEJO",label:"RETRONEJO",date:"2026-11-07T20:00:00",venue:"Wet Eventos",opened:"2026-08-28T10:00:00",capacity:3000,status:"Vendas abertas"},
 {id:"oboe25",name:"OBOÉ 2025",label:"OBOÉ",date:"2025-10-11T22:00:00",venue:"Armazém Convention",opened:"2025-07-18T12:00:00",capacity:2100,status:"Encerrado"},
 {id:"ginga25",name:"GINGA 2025",label:"GINGA",date:"2025-08-23T21:00:00",venue:"Trapiche Barnabé",opened:"2025-06-10T18:00:00",capacity:1600,status:"Encerrado"},
];
const CLIENTS:Client[]=[
 {id:"c1",name:"Marina Lima",phone:"71999110001",email:"marina@trend.com",cpf:"123.456.789-01",birth:"1999-09-03",city:"Salvador"},
 {id:"c2",name:"João Pedro",phone:"71999110002",email:"joao@trend.com",cpf:"234.567.890-12",birth:"2001-11-18",city:"Salvador"},
 {id:"c3",name:"Bruna Costa",phone:"71999110003",email:"bruna@trend.com",cpf:"345.678.901-23",birth:"1998-08-31",city:"Lauro de Freitas"},
 {id:"c4",name:"Lucas Gomes",phone:"71999110004",email:"lucas@trend.com",cpf:"456.789.012-34",birth:"2000-09-07",city:"Salvador"},
 {id:"c5",name:"Ana Clara",phone:"71999110005",email:"ana@trend.com",cpf:"567.890.123-45",birth:"2002-10-02",city:"Camaçari"},
 {id:"c6",name:"Henrique Reis",phone:"71999110006",email:"henrique@trend.com",cpf:"678.901.234-56",birth:"1997-12-11",city:"Salvador"},
 {id:"c7",name:"Rafaela Alves",phone:"71999110007",email:"rafa@trend.com",cpf:"789.012.345-67",birth:"2003-09-12",city:"Salvador"},
 {id:"c8",name:"Pedro Matos",phone:"71999110008",email:"pedro@trend.com",cpf:"890.123.456-78",birth:"1999-07-20",city:"Feira de Santana"},
];
const SALES:Sale[]=[
 ["s1","c1","oboe25","2025-07-18T13:10:00",2,520],["s2","c1","ginga25","2025-06-10T20:00:00",1,220],["s3","c1","oboe26","2026-08-20T12:18:00",2,640],
 ["s4","c2","oboe25","2025-08-01T19:20:00",3,690],["s5","c2","ginga25","2025-06-10T18:40:00",2,420],["s6","c2","ginga26","2026-08-12T18:10:00",2,520],
 ["s7","c3","oboe25","2025-10-10T23:10:00",1,320],["s8","c3","ginga25","2025-08-22T20:00:00",1,270],["s9","c3","retro26","2026-08-28T11:00:00",4,920],
 ["s10","c4","oboe25","2025-07-18T12:12:00",2,460],["s11","c4","ginga25","2025-06-10T18:20:00",2,400],["s12","c4","oboe26","2026-08-20T12:40:00",3,930],
 ["s13","c5","ginga25","2025-07-20T14:00:00",1,230],["s14","c5","ginga26","2026-08-30T21:00:00",2,540],
 ["s15","c6","oboe25","2025-07-18T13:00:00",2,500],["s16","c6","ginga25","2025-06-10T18:25:00",3,630],
 ["s17","c7","ginga26","2026-08-12T19:00:00",1,260],["s18","c8","oboe25","2025-09-02T22:00:00",4,1040],
].map(x=>({id:x[0] as string,clientId:x[1] as string,eventId:x[2] as string,at:x[3] as string,qty:x[4] as number,value:x[5] as number}));
const INITIAL:Store={events:EVENTS,clients:CLIENTS,sales:SALES,imports:[]};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const dt=(s:string)=>new Date(s).toLocaleDateString("pt-BR");
const hours=(a:string,b:string)=>(+new Date(a)-+new Date(b))/36e5;
const clean=(v:string)=>String(v||"").trim();
const digits=(v:string)=>clean(v).replace(/\D/g,"");
const norm=(v:string)=>clean(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const FIELD_OPTIONS:{key:FieldKey;label:string}[]=[{key:"ignore",label:"Ignorar"},{key:"name",label:"Nome"},{key:"cpf",label:"CPF"},{key:"phone",label:"Telefone"},{key:"email",label:"E-mail"},{key:"birth",label:"Nascimento"},{key:"city",label:"Cidade"},{key:"date",label:"Data da compra"},{key:"time",label:"Horário da compra"},{key:"qty",label:"Quantidade"},{key:"value",label:"Valor"},{key:"ticketType",label:"Tipo de ingresso"},{key:"saleId",label:"ID da venda"}];
const ALIASES:Record<Exclude<FieldKey,"ignore">,string[]>={name:["nome","nomecliente","nomedocliente","cliente","comprador","nomecomprador","nometitular","nomeparticipante","participante","participantename","nomecompleto"],cpf:["cpf","cpftitular","cpfparticipante","documento","cpfcliente","documentocliente","documentotitular"],phone:["telefone","celular","whatsapp","fone","telefonecliente","celularcliente","celulartitular","celularparticipante","telefonecomprador"],email:["email","emailcliente","emailtitular","emailparticipante","correioeletronico","emailcomprador"],birth:["nascimento","datadenascimento","datanascimento","nascimentotitular"],city:["cidade","municipio","cidadetitular"],date:["data","datacompra","datadacompra","datadavenda","datavenda","datapedido","pedidodata"],time:["hora","horario","horariodacompra","horavenda","horariovenda","horapedido","pedidohora"],qty:["quantidade","qtd","ingressos","quantidadeingressos","qtdingressos"],value:["valor","valorpago","valortotal","total","preco","valorcompra"],ticketType:["tipodeingresso","tipoingresso","lote","setor","produto","ingresso"],saleId:["iddavenda","idvenda","registro","pedido","idpedido","codigo","transacao","codigodavenda"]};
const guessField=(header:string):FieldKey=>{const n=norm(header);for(const [key,values] of Object.entries(ALIASES))if(values.includes(n))return key as FieldKey;return "ignore"};
const headerPriority=(header:string)=>/titular|comprador|cliente/.test(norm(header))?0:/participante/.test(norm(header))?2:1;
const locateHeaderRow=(matrix:string[][])=>{let best={index:-1,score:-1};matrix.slice(0,Math.min(60,matrix.length)).forEach((row,index)=>{const unique=new Set(row.map(guessField).filter(x=>x!=="ignore")),score=unique.size+(unique.has("name")?3:0)+(unique.has("date")?2:0)+((["cpf","email","phone"] as FieldKey[]).some(x=>unique.has(x))?2:0);if(score>best.score)best={index,score}});return best.score>=7?best.index:-1};
const hasRealName=(value?:string)=>!!clean(value||"")&&!/^(sem nome|nao informado|não informado|n\/a|ni)$/i.test(clean(value||""));
const parseNumber=(v:string)=>{const s=clean(v).replace(/R\$/gi,"").replace(/\s/g,"");if(!s)return 0;if(s.includes(","))return Number(s.replace(/\./g,"").replace(",","."))||0;return Number(s)||0};
const parseDateTime=(date:string,time:string)=>{const d=clean(date),t=clean(time)||"00:00";if(!d)return "";if(/^\d{4}-\d{2}-\d{2}/.test(d)){const base=d.includes("T")?d.split("T")[0]:d.slice(0,10);return `${base}T${t.slice(0,5)}`;}const m=d.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})/);if(m){const y=m[3].length===2?`20${m[3]}`:m[3];return `${y}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}T${t.slice(0,5)}`;}const x=new Date(`${d} ${t}`);return Number.isNaN(+x)?"":x.toISOString().slice(0,16)};
const findClient=(clients:Client[],cpf:string,email:string,phone:string)=>(cpf?clients.find(c=>digits(c.cpf)===digits(cpf)):undefined)||(email?clients.find(c=>clean(c.email).toLowerCase()===clean(email).toLowerCase()):undefined)||(phone?clients.find(c=>digits(c.phone)===digits(phone)):undefined);
const saleKey=(eventId:string,clientId:string,at:string,qty:number,value:number,ticketType:string,saleId:string)=>saleId?`${eventId}|id:${norm(saleId)}`:`${eventId}|${clientId}|${at}|${qty}|${value.toFixed(2)}|${norm(ticketType)}`;
const openDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open("trend-crm",1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains("state"))req.result.createObjectStore("state")};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
const dbRead=async()=>{const db=await openDb();return new Promise<Store|undefined>((resolve,reject)=>{const req=db.transaction("state","readonly").objectStore("state").get("main");req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})};
const dbWrite=async(data:Store)=>{const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("state","readwrite");tx.objectStore("state").put(data,"main");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})};
type ParsedRow={row:number;name:string;cpf:string;phone:string;email:string;birth:string;city:string;at:string;qty:number;value:number;ticketType:string;saleId:string;error?:string;duplicate?:boolean;clientId?:string};
const analyzePending=(pending:PendingImport,data:Store,eventId:string)=>{const mapped=new Set(pending.mapping.filter(x=>x!=="ignore")),missingColumns=[!mapped.has("name")?"Nome":"",!mapped.has("date")?"Data da compra":"",!(["cpf","email","phone"] as FieldKey[]).some(x=>mapped.has(x))?"CPF, e-mail ou telefone":""].filter(Boolean);const pick=(row:string[],key:FieldKey)=>pending.mapping.map((mappedKey,i)=>({mappedKey,i,value:clean(row[i]),priority:headerPriority(pending.headers[i])})).filter(x=>x.mappedKey===key&&x.value).sort((a,b)=>a.priority-b.priority)[0]?.value||"";const known=new Set(data.sales.filter(s=>s.eventId===eventId).map(s=>s.sourceKey||saleKey(s.eventId,s.clientId,s.at,s.qty,s.value,s.ticketType||"","")));const within=new Set<string>();const rows:ParsedRow[]=pending.rows.map((row,i)=>{const cpf=pick(row,"cpf"),email=pick(row,"email"),phone=pick(row,"phone"),name=pick(row,"name"),at=parseDateTime(pick(row,"date"),pick(row,"time")),qty=Math.max(0,Math.round(parseNumber(pick(row,"qty"))||1)),value=parseNumber(pick(row,"value")),ticketType=pick(row,"ticketType"),saleId=pick(row,"saleId"),existing=findClient(data.clients,cpf,email,phone);let error="";if(missingColumns.length)error=`Colunas essenciais não reconhecidas: ${missingColumns.join(", ")}`;else if(!cpf&&!email&&!phone)error="CPF, e-mail ou telefone não informado";else if(!hasRealName(name)&&!hasRealName(existing?.name))error="Nome não informado";else if(!at)error="Data da compra inválida ou não informada";else if(qty<1)error="Quantidade de ingressos inválida";else if(value<0)error="Valor da compra inválido";const clientId=existing?.id||`novo:${digits(cpf)||clean(email).toLowerCase()||digits(phone)}`,key=error?"":saleKey(eventId,clientId,at,qty,value,ticketType,saleId),duplicate=!!key&&(known.has(key)||within.has(key));if(key)within.add(key);return{row:pending.headerRow+i+2,name:name||existing?.name||"",cpf,phone,email,birth:pick(row,"birth"),city:pick(row,"city"),at,qty,value,ticketType,saleId,error:error||undefined,duplicate,clientId:existing?.id}});return{rows,total:rows.length,withName:rows.filter(r=>hasRealName(r.name)).length,withoutName:rows.filter(r=>!hasRealName(r.name)).length,valid:rows.filter(r=>!r.error).length,duplicates:rows.filter(r=>r.duplicate&&!r.error).length,errors:rows.filter(r=>r.error).length,added:rows.filter(r=>!r.error&&!r.duplicate).length,missingColumns,identified:[...mapped].map(k=>FIELD_OPTIONS.find(f=>f.key===k)?.label||k)}};

export default function Home(){
 const [data,setData]=useState<Store>(INITIAL),[ready,setReady]=useState(false),[view,setView]=useState("Dashboard"),[query,setQuery]=useState(""),[eventId,setEventId]=useState("oboe26"),[importEventId,setImportEventId]=useState("oboe26"),[segment,setSegment]=useState("Todos"),[detail,setDetail]=useState<string|null>(null),[toast,setToast]=useState(""),[loading,setLoading]=useState(false),[eventForm,setEventForm]=useState<Event|null>(null),[pending,setPending]=useState<PendingImport|null>(null),[importDetail,setImportDetail]=useState<string|null>(null); const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{(async()=>{try{const saved=await dbRead();if(saved)setData({...saved,imports:saved.imports||[]});else{const old=localStorage.getItem("trend-crm-v2");if(old){const parsed=JSON.parse(old);setData({...parsed,imports:parsed.imports||[]})}}}finally{setReady(true)}})()},[]);
 useEffect(()=>{if(ready)dbWrite(data).catch(()=>setToast("Erro ao salvar no banco local"))},[data,ready]);
 const event= data.events.find(e=>e.id===eventId)||data.events[0];
 const stats=useMemo(()=>data.clients.map(c=>{const ss=data.sales.filter(s=>s.clientId===c.id),ev=new Set(ss.map(s=>s.eventId)),spent=ss.reduce((a,s)=>a+s.value,0),qty=ss.reduce((a,s)=>a+s.qty,0),early=ss.filter(s=>{const e=data.events.find(x=>x.id===s.eventId);return e&&hours(s.at,e.opened)<=24}).length,last=ss.map(s=>s.at).sort().at(-1)||"";const recency=last?Math.max(0,1-(Date.now()-+new Date(last))/(365*864e5)):0;const score=Math.min(100,Math.round(ev.size*12+Math.min(spent/80,25)+early*8+Math.min(qty*2,15)+recency*15));return{...c,sales:ss,events:ev.size,spent,qty,early,last,score,ticket:ss.length?spent/ss.length:0,class:score>90?"Super cliente":score>70?"VIP":score>50?"Engajado":score>30?"Recorrente":"Ocasional"}}),[data]);
 const active=data.events.filter(e=>(e.lifecycle||"active")==="active"&&new Date(e.date)>new Date("2026-08-31")); const es=data.sales.filter(s=>s.eventId===event.id),buyers=new Set(es.map(s=>s.clientId)),sold=es.reduce((a,s)=>a+s.qty,0),revenue=es.reduce((a,s)=>a+s.value,0);
 const filtered=stats.filter(c=>{const text=(c.name+c.phone+c.email+c.cpf+c.sales.map(s=>data.events.find(e=>e.id===s.eventId)?.name).join(" ")).toLowerCase();const ok=text.includes(query.toLowerCase());if(segment==="VIP")return ok&&c.score>=71;if(segment==="Early Buyers")return ok&&c.early>0;if(segment==="Adormecidos")return ok&&c.events>=2&&!c.sales.some(s=>buyers.has(c.id)&&s.eventId===event.id);if(segment==="Ainda não comprou")return ok&&c.events>=2&&!buyers.has(c.id);return ok});
 const flash=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2600)};
 const exportList=(kind:"csv"|"xls")=>{const rows=filtered.map(c=>[c.name,c.phone,c.email,c.cpf,c.events,c.early,c.score,money(c.spent)]);const head=["Nome","Telefone","E-mail","CPF","Eventos","Early buyers","Score","Gasto"];
  let blob:Blob;if(kind==="csv")blob=new Blob(["\ufeff"+[head,...rows].map(r=>r.join(";")).join("\n")],{type:"text/csv"});else blob=new Blob([`<table>${[head,...rows].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</table>`],{type:"application/vnd.ms-excel"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`trend-${segment.toLowerCase().replaceAll(" ","-")}.${kind}`;a.click();flash(`${filtered.length} contatos exportados`)};
 const readMailing=async(f:File)=>{setLoading(true);try{if(!data.events.some(e=>e.id===importEventId))throw new Error("Selecione um evento");const ext=f.name.split(".").pop()?.toLowerCase();if(ext!=="csv"&&ext!=="xlsx")throw new Error("Formato não aceito. Envie um arquivo CSV ou XLSX.");const wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true,cellText:true}),sheetName=wb.SheetNames[0];if(!sheetName)throw new Error("A planilha não possui nenhuma aba");const sheet=wb.Sheets[sheetName],matrix=XLSX.utils.sheet_to_json<(string|number|Date)[]>(sheet,{header:1,raw:false,defval:"",dateNF:"yyyy-mm-dd",blankrows:false}).map(r=>r.map(v=>v instanceof Date?v.toISOString():clean(String(v))));if(matrix.length<2)throw new Error("O arquivo não possui registros para importar");const headerRow=locateHeaderRow(matrix);if(headerRow<0)throw new Error("Não encontramos um cabeçalho válido. O arquivo precisa ter Nome, Data da compra e ao menos CPF, E-mail ou Telefone.");const width=Math.max(...matrix.slice(headerRow).map(r=>r.length)),headers=Array.from({length:width},(_,i)=>clean(matrix[headerRow]?.[i])||`Coluna ${i+1}`),rows=matrix.slice(headerRow+1).map(r=>Array.from({length:width},(_,i)=>clean(r[i]))).filter(r=>r.some(Boolean)),mapping=headers.map(guessField);if(!mapping.includes("name"))throw new Error("A coluna de Nome não foi reconhecida. Revise o cabeçalho antes de importar.");setPending({fileName:f.name,format:ext==="xlsx"?"XLSX":"CSV",sheetName,headerRow,headers,rows,mapping});setImportDetail(null)}catch(e){flash(e instanceof Error?e.message:"Não foi possível ler o arquivo")}finally{setLoading(false)}};
 const preview=useMemo(()=>pending?analyzePending(pending,data,importEventId):null,[pending,data,importEventId]);
 const confirmImport=()=>{if(!pending||!preview)return;if(preview.missingColumns.length){flash(`Revise o mapeamento: falta ${preview.missingColumns.join(", ")}`);return}const importId=crypto.randomUUID(),nextClients=[...data.clients],nextSales=[...data.sales],saleIds:string[]=[],createdClientIds:string[]=[];for(const row of preview.rows){if(row.error||row.duplicate)continue;let c=findClient(nextClients,row.cpf,row.email,row.phone);if(!c){c={id:crypto.randomUUID(),name:row.name,phone:row.phone,email:row.email,cpf:row.cpf,birth:row.birth,city:row.city};nextClients.push(c);createdClientIds.push(c.id)}else{const merged={...c,name:hasRealName(c.name)?c.name:row.name,cpf:c.cpf||row.cpf,email:c.email||row.email,phone:c.phone||row.phone,birth:c.birth||row.birth,city:c.city||row.city};nextClients[nextClients.findIndex(x=>x.id===c!.id)]=merged;c=merged}const sourceKey=saleKey(importEventId,c.id,row.at,row.qty,row.value,row.ticketType,row.saleId);if(nextSales.some(s=>(s.sourceKey||saleKey(s.eventId,s.clientId,s.at,s.qty,s.value,s.ticketType||"",""))===sourceKey))continue;const id=crypto.randomUUID();nextSales.push({id,clientId:c.id,eventId:importEventId,at:row.at,qty:row.qty,value:row.value,ticketType:row.ticketType,importId,sourceKey});saleIds.push(id)}const history:ImportHistory={id:importId,eventId:importEventId,fileName:pending.fileName,importedAt:new Date().toISOString(),total:preview.total,valid:preview.valid,added:saleIds.length,duplicates:preview.duplicates,errors:preview.errors,status:"Concluída",saleIds,createdClientIds,errorRows:preview.rows.filter(r=>r.error).map(r=>({row:r.row,reason:r.error!}))};setData({...data,clients:nextClients,sales:nextSales,imports:[history,...data.imports]});setPending(null);flash(`${saleIds.length} novas vendas importadas; ${preview.duplicates} duplicadas ignoradas`)};
 const undoImport=(id:string)=>{const imp=data.imports.find(x=>x.id===id);if(!imp||imp.status!=="Concluída")return;if(!confirm(`Desfazer a importação ${imp.fileName}? Apenas os ${imp.added} registros adicionados por ela serão removidos.`))return;const sales=data.sales.filter(s=>!imp.saleIds.includes(s.id)),used=new Set(sales.map(s=>s.clientId)),clients=data.clients.filter(c=>!imp.createdClientIds.includes(c.id)||used.has(c.id));setData({...data,sales,clients,imports:data.imports.map(x=>x.id===id?{...x,status:"Desfeita"}:x)});setImportDetail(null);flash("Importação desfeita sem afetar outros históricos")};
 const clearEventMailing=(id:string)=>{const target=data.events.find(e=>e.id===id);if(!target)return;if(!confirm(`Tem certeza que deseja limpar todo o mailing de ${target.name}?\n\nEssa ação removerá todas as vendas e registros importados vinculados a este evento.`))return;if(!confirm(`CONFIRMAÇÃO FINAL\n\nLimpar ${target.name} e deixá-lo vazio para um novo mailing?`))return;const removed=new Set(data.sales.filter(s=>s.eventId===id).map(s=>s.id));setData({...data,sales:data.sales.filter(s=>s.eventId!==id),imports:data.imports.map(x=>x.eventId===id&&x.status==="Concluída"?{...x,status:"Removida",saleIds:x.saleIds.filter(s=>!removed.has(s))}:x)});flash(`Mailing de ${target.name} limpo. O evento foi preservado.`)};
 const saveEvent=(ev:Event)=>{if(!ev.name.trim()||!ev.label.trim()||!ev.date||!ev.opened||!ev.venue.trim()||!ev.city?.trim()){flash("Preencha todos os campos obrigatórios");return}const exists=data.events.some(e=>e.id===ev.id);setData({...data,events:exists?data.events.map(e=>e.id===ev.id?ev:e):[ev,...data.events]});setEventForm(null);setEventId(ev.id);setImportEventId(ev.id);flash(exists?"Evento atualizado sem perder o histórico":"Evento criado e pronto para receber mailings")};
 const lifecycle=(id:string,next:Event["lifecycle"])=>{setData({...data,events:data.events.map(e=>e.id===id?{...e,lifecycle:next}:e)});flash(next==="paused"?"Evento interrompido":next==="archived"?"Evento arquivado":"Evento reativado")};
 const nav=["Dashboard","Eventos ativos","Clientes","Early Buyers","Quem ainda não comprou","Adormecidos","Inteligência","Mailing","Importação","Como importar"];
 const go=(v:string)=>{setView(v);setDetail(null);if(v==="Early Buyers")setSegment("Early Buyers");else if(v==="Quem ainda não comprou")setSegment("Ainda não comprou");else if(v==="Adormecidos")setSegment("Adormecidos")};
 return <main className="appShell"><aside><div className="logo"><b>T</b><span>TREND<small>AUDIENCE INTELLIGENCE</small></span></div><nav>{nav.map((n,i)=><button className={view===n?"on":""} onClick={()=>go(n)} key={n}><i>{["⌂","◈","♙","⚡","◎","☾","✦","▤","⇧","?"][i]}</i>{n}</button>)}</nav><div className="sync"><span/> Base salva neste dispositivo</div></aside><section className="workspace">
  <header><div><small>CRM / {view.toUpperCase()}</small><h1>{view}</h1></div><label className="globalSearch">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, telefone, e-mail, CPF ou evento"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</label><button className="cta" onClick={()=>go("Importação")}>＋ Importar</button></header>
  {view==="Dashboard"&&<Dashboard active={active} data={data} stats={stats} onEvent={id=>{setEventId(id);setDetail(id);setView("Eventos ativos")}} onGo={go}/>} 
  {view==="Eventos ativos"&&(!detail?<Events events={data.events} data={data} onOpen={id=>{setEventId(id);setDetail(id)}} onCreate={()=>setEventForm({id:crypto.randomUUID(),name:"",label:"",date:"",venue:"",city:"",opened:"",capacity:0,status:"Vendas abertas",lifecycle:"active"})} onEdit={setEventForm} onLifecycle={lifecycle}/>:<EventDetail event={event} data={data} stats={stats} onBack={()=>setDetail(null)} onMiss={()=>{setSegment("Ainda não comprou");setView("Quem ainda não comprou");setDetail(null)}} onImport={()=>{setImportEventId(event.id);setView("Importação");setDetail(null)}} onClear={()=>clearEventMailing(event.id)} onHistory={id=>{setImportDetail(id);setImportEventId(event.id);setView("Importação");setDetail(null)}}/>)}
  {["Clientes","Early Buyers","Quem ainda não comprou","Adormecidos"].includes(view)&&<Clients title={view} rows={filtered} events={data.events} onDetail={id=>setDetail(id)} detail={detail} onBack={()=>setDetail(null)} onDelete={id=>{if(confirm("Excluir este cliente e todo o histórico?")){setData({...data,clients:data.clients.filter(c=>c.id!==id),sales:data.sales.filter(s=>s.clientId!==id)});setDetail(null);flash("Cliente excluído")}}}/>} 
  {view==="Inteligência"&&<Intelligence data={data} stats={stats} event={event}/>} 
  {view==="Mailing"&&<Mailing segment={segment} setSegment={setSegment} count={filtered.length} exportList={exportList}/>} 
  {view==="Importação"&&<Import events={data.events} eventId={importEventId} setEventId={id=>{setImportEventId(id);setPending(null);setImportDetail(null)}} onPick={()=>file.current?.click()} loading={loading} imports={data.imports} onOpen={setImportDetail} openId={importDetail} onClose={()=>setImportDetail(null)} onUndo={undoImport} onClear={()=>clearEventMailing(importEventId)}/>} 
  {view==="Como importar"&&<HowToImport/>}
  <input ref={file} hidden type="file" accept=".csv,.xlsx" onChange={e=>{if(e.target.files?.[0])readMailing(e.target.files[0]);e.currentTarget.value=""}}/>{eventForm&&<EventModal value={eventForm} onChange={setEventForm} onSave={saveEvent} onClose={()=>setEventForm(null)}/>} {pending&&preview&&<ImportPreview pending={pending} setPending={setPending} preview={preview} event={data.events.find(e=>e.id===importEventId)!} onCancel={()=>setPending(null)} onConfirm={confirmImport}/>} {toast&&<div className="toast">✓ {toast}</div>}
 </section></main>
}

function Metric({label,value,note}:{label:string,value:string|number,note?:string}){return <article className="metric"><small>{label}</small><b>{value}</b>{note&&<span>{note}</span>}</article>}
function Dashboard({active,data,stats,onEvent,onGo}:{active:Event[];data:Store;stats:any[];onEvent:(x:string)=>void;onGo:(x:string)=>void}){const rev=data.sales.reduce((a,s)=>a+s.value,0),today=data.sales.filter(s=>s.at.slice(0,10)==="2026-08-31").reduce((a,s)=>a+s.value,0);return <><div className="metrics"><Metric label="CLIENTES TOTAIS" value={stats.length}/><Metric label="RECORRENTES" value={stats.filter(c=>c.events>=2).length}/><Metric label="VIPs" value={stats.filter(c=>c.score>=71).length}/><Metric label="EARLY BUYERS" value={stats.filter(c=>c.early).length}/><Metric label="FATURAMENTO" value={money(rev)}/><Metric label="VENDAS HOJE" value={money(today)} note="tempo real"/></div><div className="sectionHead"><div><small>AGORA</small><h2>Eventos ativos</h2></div><button onClick={()=>onGo("Eventos ativos")}>Ver todos →</button></div><div className="eventGrid">{active.map(e=><EventCard key={e.id} e={e} data={data} onOpen={onEvent}/>)}</div><div className="dashboardGrid"><article className="panel"><div className="sectionHead"><h2>Top clientes TREND</h2><button onClick={()=>onGo("Clientes")}>Ranking completo →</button></div>{[...stats].sort((a,b)=>b.score-a.score).slice(0,5).map((c,i)=><div className="rank" key={c.id}><i>{i+1}</i><span><b>{c.name}</b><small>{c.class}</small></span><strong>{c.score}</strong></div>)}</article><article className="panel insight"><small>ALERTA COMERCIAL</small><b>{stats.filter(c=>c.events>=2&&!c.sales.some((s:Sale)=>s.eventId===active[0]?.id)).length} clientes recorrentes</b><p>ainda não compraram {active[0]?.name}. Priorize quem tem score acima de 70.</p><button className="cta" onClick={()=>onGo("Quem ainda não comprou")}>Criar lista agora →</button></article></div></>}
function EventCard({e,data,onOpen,onEdit,onLifecycle}:{e:Event;data:Store;onOpen:(x:string)=>void;onEdit?:(e:Event)=>void;onLifecycle?:(id:string,s:Event["lifecycle"])=>void}){const s=data.sales.filter(x=>x.eventId===e.id),sold=s.reduce((a,x)=>a+x.qty,0),rev=s.reduce((a,x)=>a+x.value,0),days=Math.ceil((+new Date(e.date)-+new Date("2026-08-31"))/864e5),life=e.lifecycle||"active";return <article className={`eventCard ${life!=="active"?"inactive":""}`}><div className="eventTop"><span className="status">● {life==="paused"?"Interrompido":life==="archived"?"Arquivado":e.status}</span><small>{days>0?`${days} DIAS`:"HISTÓRICO"}</small></div><h3>{e.name}</h3><p>{dt(e.date)} · {e.venue}{e.city?` · ${e.city}`:""}</p><div className="eventId">ID: {e.id}</div><div className="progress"><i style={{width:`${Math.min(100,sold/Math.max(1,e.capacity)*100)}%`}}/></div><div className="eventNums"><span><b>{sold}</b><small>ingressos</small></span><span><b>{money(rev)}</b><small>faturamento</small></span><span><b>{new Set(s.map(x=>x.clientId)).size}</b><small>compradores</small></span></div><button onClick={()=>onOpen(e.id)}>Ver detalhes →</button>{onEdit&&onLifecycle&&<div className="eventActions"><button onClick={()=>onEdit({...e})}>Editar</button>{life==="active"?<button onClick={()=>onLifecycle(e.id,"paused")}>Interromper</button>:<button onClick={()=>onLifecycle(e.id,"active")}>Reativar</button>}{life!=="archived"&&<button onClick={()=>confirm("Arquivar este evento? O histórico será preservado.")&&onLifecycle(e.id,"archived")}>Arquivar</button>}</div>}</article>}
function Events({events,data,onOpen,onCreate,onEdit,onLifecycle}:{events:Event[];data:Store;onOpen:(x:string)=>void;onCreate:()=>void;onEdit:(e:Event)=>void;onLifecycle:(id:string,s:Event["lifecycle"])=>void}){const [scope,setScope]=useState("Ativos");const visible=events.filter(e=>scope==="Todos"?true:scope==="Arquivados"?(e.lifecycle==="archived"):(e.lifecycle||"active")==="active"&&new Date(e.date)>new Date("2026-08-31"));return <><div className="pageIntro manageIntro"><div><h2>O pulso das vendas, evento por evento.</h2><p>Crie, edite e gerencie eventos sem romper nenhum vínculo histórico.</p></div><button className="cta" onClick={onCreate}>＋ Criar evento</button></div><div className="scopeTabs">{["Ativos","Todos","Arquivados"].map(x=><button className={scope===x?"selected":""} onClick={()=>setScope(x)} key={x}>{x}</button>)}</div>{visible.length?<div className="eventGrid">{visible.map(e=><EventCard key={e.id} e={e} data={data} onOpen={onOpen} onEdit={onEdit} onLifecycle={onLifecycle}/>)}</div>:<div className="empty"><b>Nenhum evento nesta categoria</b><p>Crie um evento ou altere o filtro.</p></div>}</>}
function EventDetail({event,data,stats,onBack,onMiss,onImport,onClear,onHistory}:{event:Event;data:Store;stats:any[];onBack:()=>void;onMiss:()=>void;onImport:()=>void;onClear:()=>void;onHistory:(id:string)=>void}){const ss=data.sales.filter(s=>s.eventId===event.id),sold=ss.reduce((a,s)=>a+s.qty,0),rev=ss.reduce((a,s)=>a+s.value,0),buyers=new Set(ss.map(s=>s.clientId)),early=ss.filter(s=>hours(s.at,event.opened)<=24).length,history=data.imports.filter(i=>i.eventId===event.id);return <><button className="back" onClick={onBack}>← Voltar aos eventos</button><div className="eventHero"><div><span className="status">● {event.status}</span><h2>{event.name}</h2><p>{dt(event.date)} · {event.venue}</p></div><button className="cta" onClick={onMiss}>Quem ainda não comprou →</button></div><div className="metrics"><Metric label="TOTAL VENDIDO" value={sold}/><Metric label="FATURAMENTO" value={money(rev)}/><Metric label="COMPRADORES" value={buyers.size}/><Metric label="TICKET MÉDIO" value={money(buyers.size?rev/buyers.size:0)}/><Metric label="PRIMEIRAS 24H" value={early}/><Metric label="PROJEÇÃO FINAL" value={Math.round(sold*1.82)} note="estimativa histórica"/></div><div className="dashboardGrid"><article className="panel"><h3>Velocidade de vendas</h3><div className="bars">{[24,46,31,68,54,82,72].map((x,i)=><i key={i} style={{height:`${x}%`}}><small>{["25","26","27","28","29","30","31"][i]}</small></i>)}</div></article><article className="panel"><h3>Perfil dos compradores</h3><div className="donut"><b>{Math.round((stats.filter(c=>buyers.has(c.id)&&c.events>1).length/Math.max(1,buyers.size))*100)}%</b><span>recorrentes</span></div><p className="muted">{stats.filter(c=>buyers.has(c.id)&&c.score>=71).length} VIPs · {stats.filter(c=>buyers.has(c.id)&&c.events===1).length} novos clientes</p></article></div><article className="panel eventImports"><div className="sectionHead"><div><small>BASE DO EVENTO</small><h2>Mailing / Importações</h2></div><div className="importActions"><button className="cta" onClick={onImport}>＋ Importar CSV ou XLSX</button><button className="riskButton" onClick={onClear} disabled={!ss.length}>Limpar mailing do evento</button></div></div><p className="muted">{ss.length} vendas registradas · {history.length} importações no histórico</p>{history.slice(0,3).map(i=><button className="historyMini" key={i.id} onClick={()=>onHistory(i.id)}><span><b>{i.fileName}</b><small>{new Date(i.importedAt).toLocaleString("pt-BR")}</small></span><strong>{i.added} novas · {i.status}</strong></button>)}</article></>}
function Clients({title,rows,events,onDetail,detail,onBack,onDelete}:{title:string;rows:any[];events:Event[];onDetail:(x:string)=>void;detail:string|null;onBack:()=>void;onDelete:(x:string)=>void}){const c=rows.find(x=>x.id===detail);if(c)return <><button className="back" onClick={onBack}>← Voltar</button><div className="clientHero"><div className="bigAvatar">{c.name.split(" ").map((x:string)=>x[0]).join("")}</div><div><span className="status">{c.class}</span><h2>{c.name}</h2><p>{c.email} · {c.phone} · {c.city}</p></div><div className="score"><b>{c.score}</b><small>CLIENT SCORE</small></div></div><div className="metrics"><Metric label="EVENTOS" value={c.events}/><Metric label="TOTAL GASTO" value={money(c.spent)}/><Metric label="TICKET MÉDIO" value={money(c.ticket)}/><Metric label="INGRESSOS" value={c.qty}/><Metric label="EARLY BUYER" value={`${Math.round(c.early/Math.max(1,c.sales.length)*100)}%`}/></div><article className="panel"><div className="sectionHead"><h2>Histórico de compras</h2><button className="danger" onClick={()=>onDelete(c.id)}>Excluir cliente</button></div>{[...c.sales].reverse().map((s:Sale)=><div className="timeline" key={s.id}><i/><span><b>{events.find(e=>e.id===s.eventId)?.name}</b><small>{dt(s.at)} · {s.qty} ingresso(s)</small></span><strong>{money(s.value)}</strong></div>)}</article></>;return <><div className="pageIntro"><h2>{title}</h2><p>{rows.length} clientes encontrados. Clique em qualquer pessoa para abrir o perfil completo.</p></div>{rows.length?<div className="dataTable"><div className="trow thead"><span>CLIENTE</span><span>EVENTOS</span><span>EARLY</span><span>GASTO</span><span>SCORE</span></div>{rows.map(c=><button className="trow" key={c.id} onClick={()=>onDetail(c.id)}><span><b>{c.name}</b><small>{c.email}</small></span><span>{c.events}</span><span>{c.early}</span><span>{money(c.spent)}</span><span><i className="scorePill">{c.score}</i></span></button>)}</div>:<div className="empty"><b>Nenhum cliente encontrado</b><p>Limpe a busca ou altere o segmento.</p></div>}</>}
function Intelligence({data,stats,event}:{data:Store;stats:any[];event:Event}){const missing=stats.filter(c=>c.events>=2&&!c.sales.some((s:Sale)=>s.eventId===event.id));return <><div className="pageIntro"><h2>Insights que pedem ação.</h2><p>Todos os sinais abaixo são calculados a partir da base atual.</p></div><div className="insightGrid"><article><i>01</i><b>{missing.filter(c=>c.score>=71).length} clientes VIP ainda não compraram {event.label}.</b><p>Lista prioritária para ativação comercial.</p></article><article><i>02</i><b>{stats.filter(c=>c.early>=2&&!c.sales.some((s:Sale)=>s.eventId===event.id)).length} early buyers recorrentes estão ausentes.</b><p>O melhor momento de contato é agora.</p></article><article><i>03</i><b>Quinta, entre 18h e 22h, concentra o pico de compras.</b><p>Baseado no horário das vendas registradas.</p></article><article><i>04</i><b>OBOÉ e GINGA compartilham {affinity(data,"OBOÉ","GINGA")}% do público.</b><p>Alta afinidade para campanhas cruzadas.</p></article></div><article className="panel"><h3>Afinidade entre eventos</h3><div className="matrix"><span/><b>OBOÉ</b><b>GINGA</b><b>RETRONEJO</b>{["OBOÉ","GINGA","RETRONEJO"].flatMap(a=>[<b key={a}>{a}</b>,...["OBOÉ","GINGA","RETRONEJO"].map(b=><i key={a+b}>{a===b?100:affinity(data,a,b)}%</i>)] )}</div></article></>}
function affinity(data:Store,a:string,b:string){const ea=data.events.filter(e=>e.label===a).map(e=>e.id),eb=data.events.filter(e=>e.label===b).map(e=>e.id),ca=new Set(data.sales.filter(s=>ea.includes(s.eventId)).map(s=>s.clientId)),cb=new Set(data.sales.filter(s=>eb.includes(s.eventId)).map(s=>s.clientId));return Math.round([...ca].filter(x=>cb.has(x)).length/Math.max(1,ca.size)*100)}
function Mailing({segment,setSegment,count,exportList}:{segment:string;setSegment:(x:string)=>void;count:number;exportList:(x:"csv"|"xls")=>void}){return <><div className="pageIntro"><h2>Crie uma lista pronta para converter.</h2><p>Combine o segmento com a busca global e exporte o mailing.</p></div><article className="builder"><label>SEGMENTO<select value={segment} onChange={e=>setSegment(e.target.value)}>{["Todos","VIP","Early Buyers","Ainda não comprou","Adormecidos"].map(x=><option key={x}>{x}</option>)}</select></label><div className="result"><small>RESULTADO</small><b>{count}</b><span>clientes qualificados</span></div><div><button className="cta" onClick={()=>exportList("csv")}>Exportar CSV</button><button onClick={()=>exportList("xls")}>Exportar XLSX</button></div></article></>}
function Import({events,eventId,setEventId,onPick,loading,imports,onOpen,openId,onClose,onUndo,onClear}:{events:Event[];eventId:string;setEventId:(x:string)=>void;onPick:()=>void;loading:boolean;imports:ImportHistory[];onOpen:(x:string)=>void;openId:string|null;onClose:()=>void;onUndo:(x:string)=>void;onClear:()=>void}){const history=imports.filter(i=>i.eventId===eventId),selected=events.find(e=>e.id===eventId),opened=imports.find(i=>i.id===openId);return <><div className="pageIntro"><h2>Atualize a inteligência da TREND.</h2><p>Escolha o evento, envie CSV ou XLSX, revise o mapeamento e confirme somente depois da prévia.</p></div><article className="importTarget"><label>EVENTO DO MAILING<select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.name} · {dt(e.date)}{e.lifecycle==="archived"?" · ARQUIVADO":""}</option>)}</select></label><span>ID interno: <b>{eventId}</b></span></article><button className="dropzone" onClick={onPick} disabled={loading||!eventId}>{loading?<><b>Processando...</b><span>Lendo e validando o arquivo</span></>:<><b>⇧ Escolher mailing CSV ou XLSX</b><span>Nenhum dado será salvo antes do mapeamento, da prévia e da sua confirmação.</span></>}</button><article className="panel importHistory"><div className="sectionHead"><div><small>RASTREABILIDADE</small><h2>Histórico de importações</h2></div><button className="riskButton" onClick={onClear} disabled={!selected}>Limpar mailing de {selected?.label}</button></div>{history.length?<div className="historyList">{history.map(i=><button key={i.id} onClick={()=>onOpen(i.id)}><span><b>{i.fileName}</b><small>{new Date(i.importedAt).toLocaleString("pt-BR")}</small></span><span>{i.total} registros</span><span>{i.added} novos</span><span>{i.duplicates} duplicados</span><i className={`historyStatus ${i.status.toLowerCase()}`}>{i.status}</i></button>)}</div>:<div className="empty compact"><b>Nenhuma importação para este evento</b><p>O histórico aparecerá aqui após a primeira confirmação.</p></div>}</article>{opened&&<div className="modalBackdrop"><article className="modal importDetail"><div className="modalHead"><div><small>DETALHES DA IMPORTAÇÃO</small><h2>{opened.fileName}</h2></div><button onClick={onClose}>×</button></div><p className="muted">{events.find(e=>e.id===opened.eventId)?.name} · {new Date(opened.importedAt).toLocaleString("pt-BR")}</p><div className="previewMetrics"><Metric label="REGISTROS" value={opened.total}/><Metric label="ADICIONADOS" value={opened.added}/><Metric label="DUPLICADOS" value={opened.duplicates}/><Metric label="ERROS" value={opened.errors}/></div>{opened.errorRows.length>0&&<div className="errorList">{opened.errorRows.slice(0,30).map(e=><p key={e.row}><b>Linha {e.row}</b>{e.reason}</p>)}</div>}<div className="modalFoot"><button onClick={onClose}>Fechar</button>{opened.status==="Concluída"&&<button className="riskButton" onClick={()=>onUndo(opened.id)}>Desfazer importação</button>}</div></article></div>}</>}
function ImportPreview({pending,setPending,preview,event,onCancel,onConfirm}:{pending:PendingImport;setPending:(p:PendingImport)=>void;preview:ReturnType<typeof analyzePending>;event:Event;onCancel:()=>void;onConfirm:()=>void}){const change=(i:number,key:FieldKey)=>setPending({...pending,mapping:pending.mapping.map((x,n)=>n===i?key:x)}),blocked=preview.missingColumns.length>0;return <div className="modalBackdrop"><article className="modal importPreview"><div className="modalHead"><div><small>MAPEAMENTO E PRÉVIA</small><h2>{pending.fileName}</h2></div><button onClick={onCancel}>×</button></div><p className="muted">Destino: <b>{event.name}</b> · {pending.format} · aba {pending.sheetName} · cabeçalho na linha {pending.headerRow+1}</p><div className="identifiedColumns"><b>Colunas identificadas</b><span>{preview.identified.join(" · ")||"Nenhuma coluna reconhecida"}</span></div>{blocked&&<div className="mappingWarning"><b>Revise antes de importar</b><span>Não reconhecemos: {preview.missingColumns.join(", ")}. Selecione manualmente a coluna correta abaixo.</span></div>}<div className="mappingGrid">{pending.headers.map((h,i)=><label key={`${h}-${i}`}><span>{h}</span><select value={pending.mapping[i]} onChange={e=>change(i,e.target.value as FieldKey)}>{FIELD_OPTIONS.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>)}</div><div className="previewMetrics seven"><Metric label="ENCONTRADOS" value={preview.total}/><Metric label="COM NOME" value={preview.withName}/><Metric label="SEM NOME" value={preview.withoutName}/><Metric label="VÁLIDOS" value={preview.valid}/><Metric label="NOVOS" value={preview.added}/><Metric label="DUPLICADOS" value={preview.duplicates}/><Metric label="ERROS" value={preview.errors}/></div><div className="previewTable"><div className="previewRow previewHead"><span>LINHA</span><span>CLIENTE</span><span>DATA</span><span>QTD.</span><span>VALOR</span><span>STATUS</span></div>{preview.rows.slice(0,12).map(r=><div className="previewRow" key={r.row}><span>{r.row}</span><span><b>{r.name||"Sem nome"}</b><small>{r.cpf||r.email||r.phone||"Sem identificador"}</small></span><span>{r.at?new Date(r.at).toLocaleString("pt-BR"):"—"}</span><span>{r.qty}</span><span>{money(r.value)}</span><span className={r.error?"rowError":r.duplicate?"rowDuplicate":"rowValid"}>{r.error||(r.duplicate?"Duplicado":"Válido")}</span></div>)}</div>{preview.errors>0&&<div className="errorList">{preview.rows.filter(r=>r.error).slice(0,20).map(r=><p key={r.row}><b>Linha {r.row}</b>{r.error}</p>)}</div>}<div className="modalFoot"><button onClick={onCancel}>Cancelar</button><button className="cta" onClick={onConfirm} disabled={blocked||!preview.added}>{blocked?"Corrija o mapeamento":`Confirmar ${preview.added} registros`}</button></div></article></div>}
function HowToImport(){const columns=["Nome","CPF","Telefone","E-mail","Nascimento","Cidade","Data da compra","Horário da compra","Quantidade","Valor","Tipo de ingresso","ID da venda"];return <><div className="pageIntro"><h2>Como importar</h2><p>O CRM aceita CSV e XLSX diretamente. A primeira aba do XLSX será lida e nenhum dado será salvo antes da sua confirmação.</p></div><div className="howGrid"><article className="panel"><small>FORMATOS ACEITOS</small><h3>CSV ou XLSX</h3><p>O cabeçalho pode estar depois de linhas de relatório. O sistema procura automaticamente a linha correta e ignora células vazias.</p></article><article className="panel"><small>IDENTIFICAÇÃO</small><h3>CPF → E-mail → Telefone</h3><p>Esses campos evitam clientes duplicados. Telefones e identificadores são tratados como texto para preservar zeros iniciais.</p></article><article className="panel"><small>VALIDAÇÃO</small><h3>Prévia obrigatória</h3><p>Confira colunas, exemplos, registros com e sem nome, duplicados e erros antes de confirmar.</p></article></div><article className="panel columnGuide"><div className="sectionHead"><div><small>PADRÃO RECOMENDADO</small><h2>Colunas do mailing</h2></div></div><div>{columns.map((c,i)=><span key={c}><b>{c}</b><small>{i===0||i===6?"Essencial":i===1||i===2||i===3?"Ao menos um":"Opcional"}</small></span>)}</div><p>Também reconhecemos variações como Nome Cliente, Nome Titular, Nome Participante, Celular, WhatsApp, E-mail Cliente, Data Venda, Pedido Data, Hora Venda, Valor Pago, Produto e Registro.</p></article></>}
function EventModal({value,onChange,onSave,onClose}:{value:Event;onChange:(e:Event)=>void;onSave:(e:Event)=>void;onClose:()=>void}){const set=(k:keyof Event,v:string|number)=>onChange({...value,[k]:v});return <div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={e=>{e.preventDefault();onSave(value)}}><div className="modalHead"><div><small>{value.name?"EDITAR EVENTO":"NOVO EVENTO"}</small><h2>{value.name||"Criar evento"}</h2></div><button type="button" onClick={onClose}>×</button></div><div className="formGrid"><label>NOME<input required value={value.name} onChange={e=>set("name",e.target.value)} placeholder="Ex.: OBOÉ 4 ANOS"/></label><label>LABEL<input required value={value.label} onChange={e=>set("label",e.target.value.toUpperCase())} placeholder="Ex.: OBOÉ"/></label><label>DATA E HORA DO EVENTO<input required type="datetime-local" value={value.date} onChange={e=>set("date",e.target.value)}/></label><label>ABERTURA DAS VENDAS<input required type="datetime-local" value={value.opened} onChange={e=>set("opened",e.target.value)}/></label><label>LOCAL<input required value={value.venue} onChange={e=>set("venue",e.target.value)} placeholder="Ex.: Armazém Convention"/></label><label>CIDADE<input required value={value.city||""} onChange={e=>set("city",e.target.value)} placeholder="Ex.: Salvador"/></label><label>CAPACIDADE<input min="0" type="number" value={value.capacity||""} onChange={e=>set("capacity",+e.target.value)} placeholder="0"/></label><label>STATUS DE VENDAS<select value={value.status} onChange={e=>set("status",e.target.value)}>{["Vendas abertas","Vendas acelerando","Vendas abaixo da média","Perto de sold out","Sold out","Encerrado"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="idNotice"><b>ID interno permanente</b><span>{value.id}</span><p>Esse identificador nunca muda e protege os vínculos com clientes, vendas, mailings e históricos.</p></div><div className="modalFoot"><button type="button" onClick={onClose}>Cancelar</button><button className="cta" type="submit">Salvar evento</button></div></form></div>}
