"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Event={id:string;name:string;label:string;date:string;venue:string;opened:string;capacity:number;status:string};
type Client={id:string;name:string;phone:string;email:string;cpf:string;birth:string;city:string};
type Sale={id:string;clientId:string;eventId:string;at:string;qty:number;value:number};
type Store={events:Event[];clients:Client[];sales:Sale[]};

const EVENTS:Event[]=[
 {id:"oboe26",name:"OBOÉ 3 ANOS",label:"OBOÉ",date:"2026-10-10T22:00:00",venue:"Armazém Convention",opened:"2026-08-20T12:00:00",capacity:2400,status:"Vendas acelerando"},
 {id:"ginga26",name:"GINGA — Primavera",label:"GINGA",date:"2026-09-19T21:00:00",venue:"Trapiche Barnabé",opened:"2026-08-12T18:00:00",capacity:1800,status:"Perto de sold out"},
 {id:"retro26",name:"RETRONEJO",label:"RETRONEJO",date:"2026-11-07T20:00:00",venue:"Wet Eventos",opened:"2026-08-28T10:00:00",capacity:3000,status:"Vendas abertas"},
 {id:"oboe25",name:"OBOÉ 2025",label:"OBOÉ",date:"2025-10-11T22:00:00",venue:"Armazém Convention",opened:"2025-07-18T12:00:00",capacity:2100,status:"Encerrado"},
 {id:"ginga25",name:"GINGA 2025",label:"GINGA",date:"2025-08-23T21:00:00",venue:"Trapiche Barnabé",opened:"2025-06-10T18:00:00",capacity:1600,status:"Encerrado"},
];
const CLIENTS:Client[]=[
 {id:"c1",name:"Marina Lima",phone:"71999110001",email:"marina@trend.com",cpf:"123.456.789-01",birth:"1999-09-03",city:"Salvador"},
 {id:"c2",name:"João Pedro",phone:"71999110002",email:"joao@trend.com",cpf:"234.567.890-12",birth:"2001-11-18",city:"Salvador"},
 {id:"c3",name:"Bruna Costa",phone:"71999110003",email:"bruna@trend.com",cpf:"345.678.901-23",birth:"1998-08-31",city:"Lauro de Freitas"},
 {id:"c4",name:"Lucas Gomes",phone:"71999110004",email:"lucas@trend.com",cpf:"456.789.012-34",birth:"2000-09-07",city:"Salvador"},
 {id:"c5",name:"Ana Clara",phone:"71999110005",email:"ana@trend.com",cpf:"567.890.123-45",birth:"2002-10-02",city:"Camaçari"},
 {id:"c6",name:"Henrique Reis",phone:"71999110006",email:"henrique@trend.com",cpf:"678.901.234-56",birth:"1997-12-11",city:"Salvador"},
 {id:"c7",name:"Rafaela Alves",phone:"71999110007",email:"rafa@trend.com",cpf:"789.012.345-67",birth:"2003-09-12",city:"Salvador"},
 {id:"c8",name:"Pedro Matos",phone:"71999110008",email:"pedro@trend.com",cpf:"890.123.456-78",birth:"1999-07-20",city:"Feira de Santana"},
];
const SALES:Sale[]=[
 ["s1","c1","oboe25","2025-07-18T13:10:00",2,520],["s2","c1","ginga25","2025-06-10T20:00:00",1,220],["s3","c1","oboe26","2026-08-20T12:18:00",2,640],
 ["s4","c2","oboe25","2025-08-01T19:20:00",3,690],["s5","c2","ginga25","2025-06-10T18:40:00",2,420],["s6","c2","ginga26","2026-08-12T18:10:00",2,520],
 ["s7","c3","oboe25","2025-10-10T23:10:00",1,320],["s8","c3","ginga25","2025-08-22T20:00:00",1,270],["s9","c3","retro26","2026-08-28T11:00:00",4,920],
 ["s10","c4","oboe25","2025-07-18T12:12:00",2,460],["s11","c4","ginga25","2025-06-10T18:20:00",2,400],["s12","c4","oboe26","2026-08-20T12:40:00",3,930],
 ["s13","c5","ginga25","2025-07-20T14:00:00",1,230],["s14","c5","ginga26","2026-08-30T21:00:00",2,540],
 ["s15","c6","oboe25","2025-07-18T13:00:00",2,500],["s16","c6","ginga25","2025-06-10T18:25:00",3,630],
 ["s17","c7","ginga26","2026-08-12T19:00:00",1,260],["s18","c8","oboe25","2025-09-02T22:00:00",4,1040],
].map(x=>({id:x[0] as string,clientId:x[1] as string,eventId:x[2] as string,at:x[3] as string,qty:x[4] as number,value:x[5] as number}));
const INITIAL:Store={events:EVENTS,clients:CLIENTS,sales:SALES};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const dt=(s:string)=>new Date(s).toLocaleDateString("pt-BR");
const hours=(a:string,b:string)=>(+new Date(a)-+new Date(b))/36e5;

export default function Home(){
 const [data,setData]=useState<Store>(INITIAL),[view,setView]=useState("Dashboard"),[query,setQuery]=useState(""),[eventId,setEventId]=useState("oboe26"),[segment,setSegment]=useState("Todos"),[detail,setDetail]=useState<string|null>(null),[toast,setToast]=useState(""),[loading,setLoading]=useState(false); const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const x=localStorage.getItem("trend-crm-v2");if(x)setData(JSON.parse(x))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("trend-crm-v2",JSON.stringify(data))},[data]);
 const event= data.events.find(e=>e.id===eventId)||data.events[0];
 const stats=useMemo(()=>data.clients.map(c=>{const ss=data.sales.filter(s=>s.clientId===c.id),ev=new Set(ss.map(s=>s.eventId)),spent=ss.reduce((a,s)=>a+s.value,0),qty=ss.reduce((a,s)=>a+s.qty,0),early=ss.filter(s=>{const e=data.events.find(x=>x.id===s.eventId);return e&&hours(s.at,e.opened)<=24}).length,last=ss.map(s=>s.at).sort().at(-1)||"";const recency=last?Math.max(0,1-(Date.now()-+new Date(last))/(365*864e5)):0;const score=Math.min(100,Math.round(ev.size*12+Math.min(spent/80,25)+early*8+Math.min(qty*2,15)+recency*15));return{...c,sales:ss,events:ev.size,spent,qty,early,last,score,ticket:ss.length?spent/ss.length:0,class:score>90?"Super cliente":score>70?"VIP":score>50?"Engajado":score>30?"Recorrente":"Ocasional"}}),[data]);
 const active=data.events.filter(e=>new Date(e.date)>new Date("2026-08-31")); const es=data.sales.filter(s=>s.eventId===event.id),buyers=new Set(es.map(s=>s.clientId)),sold=es.reduce((a,s)=>a+s.qty,0),revenue=es.reduce((a,s)=>a+s.value,0);
 const filtered=stats.filter(c=>{const text=(c.name+c.phone+c.email+c.cpf+c.sales.map(s=>data.events.find(e=>e.id===s.eventId)?.name).join(" ")).toLowerCase();const ok=text.includes(query.toLowerCase());if(segment==="VIP")return ok&&c.score>=71;if(segment==="Early Buyers")return ok&&c.early>0;if(segment==="Adormecidos")return ok&&c.events>=2&&!c.sales.some(s=>buyers.has(c.id)&&s.eventId===event.id);if(segment==="Ainda não comprou")return ok&&c.events>=2&&!buyers.has(c.id);return ok});
 const flash=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2600)};
 const exportList=(kind:"csv"|"xls")=>{const rows=filtered.map(c=>[c.name,c.phone,c.email,c.cpf,c.events,c.early,c.score,money(c.spent)]);const head=["Nome","Telefone","E-mail","CPF","Eventos","Early buyers","Score","Gasto"];
  let blob:Blob;if(kind==="csv")blob=new Blob(["\ufeff"+[head,...rows].map(r=>r.join(";")).join("\n")],{type:"text/csv"});else blob=new Blob([`<table>${[head,...rows].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</table>`],{type:"application/vnd.ms-excel"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`trend-${segment.toLowerCase().replaceAll(" ","-")}.${kind}`;a.click();flash(`${filtered.length} contatos exportados`)};
 const importCsv=async(f:File)=>{setLoading(true);try{const text=await f.text(),lines=text.split(/\r?\n/).filter(Boolean),h=lines.shift()!.split(/[;,]/).map(x=>x.toLowerCase().trim());let added=0;const next={...data,clients:[...data.clients],sales:[...data.sales]};for(const line of lines){const v=line.split(/[;,]/),get=(n:string)=>v[h.indexOf(n)]||"",cpf=get("cpf"),email=get("email")||get("e-mail"),phone=get("telefone");let c=next.clients.find(x=>(cpf&&x.cpf===cpf)||(email&&x.email===email)||(phone&&x.phone===phone));if(!c){c={id:`c${Date.now()}${added}`,name:get("nome")||"Sem nome",phone,email,cpf,birth:get("nascimento"),city:get("cidade")};next.clients.push(c);added++}const ev=next.events.find(e=>e.name.toLowerCase().includes(get("evento").toLowerCase()));if(ev&&get("valor"))next.sales.push({id:`s${Date.now()}${next.sales.length}`,clientId:c.id,eventId:ev.id,at:get("data")||new Date().toISOString(),qty:+get("quantidade")||1,value:+get("valor").replace(",",".")||0})}setData(next);flash(`${added} novos clientes importados`)}catch{flash("Erro ao importar arquivo")}finally{setLoading(false)}};
 const nav=["Dashboard","Eventos ativos","Clientes","Early Buyers","Quem ainda não comprou","Adormecidos","Inteligência","Mailing","Importação"];
 const go=(v:string)=>{setView(v);setDetail(null);if(v==="Early Buyers")setSegment("Early Buyers");else if(v==="Quem ainda não comprou")setSegment("Ainda não comprou");else if(v==="Adormecidos")setSegment("Adormecidos")};
 return <main className="appShell"><aside><div className="logo"><b>T</b><span>TREND<small>AUDIENCE INTELLIGENCE</small></span></div><nav>{nav.map((n,i)=><button className={view===n?"on":""} onClick={()=>go(n)} key={n}><i>{["⌂","◈","♙","⚡","◎","☾","✦","▤","⇧"][i]}</i>{n}</button>)}</nav><div className="sync"><span/> Base salva neste dispositivo</div></aside><section className="workspace">
  <header><div><small>CRM / {view.toUpperCase()}</small><h1>{view}</h1></div><label className="globalSearch">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, telefone, e-mail, CPF ou evento"/>{query&&<button onClick={()=>setQuery("")}>×</button>}</label><button className="cta" onClick={()=>file.current?.click()}>＋ Importar</button></header>
  {view==="Dashboard"&&<Dashboard active={active} data={data} stats={stats} onEvent={id=>{setEventId(id);setDetail(id);setView("Eventos ativos")}} onGo={go}/>} 
  {view==="Eventos ativos"&&(!detail?<Events events={active} data={data} onOpen={id=>{setEventId(id);setDetail(id)}}/>:<EventDetail event={event} data={data} stats={stats} onBack={()=>setDetail(null)} onMiss={()=>{setSegment("Ainda não comprou");setView("Quem ainda não comprou");setDetail(null)}}/>)}
  {["Clientes","Early Buyers","Quem ainda não comprou","Adormecidos"].includes(view)&&<Clients title={view} rows={filtered} events={data.events} onDetail={id=>setDetail(id)} detail={detail} onBack={()=>setDetail(null)} onDelete={id=>{if(confirm("Excluir este cliente e todo o histórico?")){setData({...data,clients:data.clients.filter(c=>c.id!==id),sales:data.sales.filter(s=>s.clientId!==id)});setDetail(null);flash("Cliente excluído")}}}/>} 
  {view==="Inteligência"&&<Intelligence data={data} stats={stats} event={event}/>} 
  {view==="Mailing"&&<Mailing segment={segment} setSegment={setSegment} count={filtered.length} exportList={exportList}/>} 
  {view==="Importação"&&<Import onPick={()=>file.current?.click()} loading={loading}/>} 
  <input ref={file} hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/>{toast&&<div className="toast">✓ {toast}</div>}
 </section></main>
}

function Metric({label,value,note}:{label:string,value:string|number,note?:string}){return <article className="metric"><small>{label}</small><b>{value}</b>{note&&<span>{note}</span>}</article>}
function Dashboard({active,data,stats,onEvent,onGo}:{active:Event[];data:Store;stats:any[];onEvent:(x:string)=>void;onGo:(x:string)=>void}){const rev=data.sales.reduce((a,s)=>a+s.value,0),today=data.sales.filter(s=>s.at.slice(0,10)==="2026-08-31").reduce((a,s)=>a+s.value,0);return <><div className="metrics"><Metric label="CLIENTES TOTAIS" value={stats.length}/><Metric label="RECORRENTES" value={stats.filter(c=>c.events>=2).length}/><Metric label="VIPs" value={stats.filter(c=>c.score>=71).length}/><Metric label="EARLY BUYERS" value={stats.filter(c=>c.early).length}/><Metric label="FATURAMENTO" value={money(rev)}/><Metric label="VENDAS HOJE" value={money(today)} note="tempo real"/></div><div className="sectionHead"><div><small>AGORA</small><h2>Eventos ativos</h2></div><button onClick={()=>onGo("Eventos ativos")}>Ver todos →</button></div><div className="eventGrid">{active.map(e=><EventCard key={e.id} e={e} data={data} onOpen={onEvent}/>)}</div><div className="dashboardGrid"><article className="panel"><div className="sectionHead"><h2>Top clientes TREND</h2><button onClick={()=>onGo("Clientes")}>Ranking completo →</button></div>{[...stats].sort((a,b)=>b.score-a.score).slice(0,5).map((c,i)=><div className="rank" key={c.id}><i>{i+1}</i><span><b>{c.name}</b><small>{c.class}</small></span><strong>{c.score}</strong></div>)}</article><article className="panel insight"><small>ALERTA COMERCIAL</small><b>{stats.filter(c=>c.events>=2&&!c.sales.some((s:Sale)=>s.eventId===active[0]?.id)).length} clientes recorrentes</b><p>ainda não compraram {active[0]?.name}. Priorize quem tem score acima de 70.</p><button className="cta" onClick={()=>onGo("Quem ainda não comprou")}>Criar lista agora →</button></article></div></>}
function EventCard({e,data,onOpen}:{e:Event;data:Store;onOpen:(x:string)=>void}){const s=data.sales.filter(x=>x.eventId===e.id),sold=s.reduce((a,x)=>a+x.qty,0),rev=s.reduce((a,x)=>a+x.value,0),days=Math.ceil((+new Date(e.date)-+new Date("2026-08-31"))/864e5);return <article className="eventCard"><div className="eventTop"><span className="status">● {e.status}</span><small>{days} DIAS</small></div><h3>{e.name}</h3><p>{dt(e.date)} · {e.venue}</p><div className="progress"><i style={{width:`${Math.min(100,sold/e.capacity*100)}%`}}/></div><div className="eventNums"><span><b>{sold}</b><small>ingressos</small></span><span><b>{money(rev)}</b><small>faturamento</small></span><span><b>{new Set(s.map(x=>x.clientId)).size}</b><small>compradores</small></span></div><button onClick={()=>onOpen(e.id)}>Ver detalhes →</button></article>}
function Events({events,data,onOpen}:{events:Event[];data:Store;onOpen:(x:string)=>void}){return <><div className="pageIntro"><h2>O pulso das vendas, evento por evento.</h2><p>Acompanhe performance, velocidade e oportunidades de cada evento aberto.</p></div><div className="eventGrid">{events.map(e=><EventCard key={e.id} e={e} data={data} onOpen={onOpen}/>)}</div></>}
function EventDetail({event,data,stats,onBack,onMiss}:{event:Event;data:Store;stats:any[];onBack:()=>void;onMiss:()=>void}){const ss=data.sales.filter(s=>s.eventId===event.id),sold=ss.reduce((a,s)=>a+s.qty,0),rev=ss.reduce((a,s)=>a+s.value,0),buyers=new Set(ss.map(s=>s.clientId)),early=ss.filter(s=>hours(s.at,event.opened)<=24).length;return <><button className="back" onClick={onBack}>← Voltar aos eventos</button><div className="eventHero"><div><span className="status">● {event.status}</span><h2>{event.name}</h2><p>{dt(event.date)} · {event.venue}</p></div><button className="cta" onClick={onMiss}>Quem ainda não comprou →</button></div><div className="metrics"><Metric label="TOTAL VENDIDO" value={sold}/><Metric label="FATURAMENTO" value={money(rev)}/><Metric label="COMPRADORES" value={buyers.size}/><Metric label="TICKET MÉDIO" value={money(buyers.size?rev/buyers.size:0)}/><Metric label="PRIMEIRAS 24H" value={early}/><Metric label="PROJEÇÃO FINAL" value={Math.round(sold*1.82)} note="estimativa histórica"/></div><div className="dashboardGrid"><article className="panel"><h3>Velocidade de vendas</h3><div className="bars">{[24,46,31,68,54,82,72].map((x,i)=><i key={i} style={{height:`${x}%`}}><small>{["25","26","27","28","29","30","31"][i]}</small></i>)}</div></article><article className="panel"><h3>Perfil dos compradores</h3><div className="donut"><b>{Math.round((stats.filter(c=>buyers.has(c.id)&&c.events>1).length/Math.max(1,buyers.size))*100)}%</b><span>recorrentes</span></div><p className="muted">{stats.filter(c=>buyers.has(c.id)&&c.score>=71).length} VIPs · {stats.filter(c=>buyers.has(c.id)&&c.events===1).length} novos clientes</p></article></div></>}
function Clients({title,rows,events,onDetail,detail,onBack,onDelete}:{title:string;rows:any[];events:Event[];onDetail:(x:string)=>void;detail:string|null;onBack:()=>void;onDelete:(x:string)=>void}){const c=rows.find(x=>x.id===detail);if(c)return <><button className="back" onClick={onBack}>← Voltar</button><div className="clientHero"><div className="bigAvatar">{c.name.split(" ").map((x:string)=>x[0]).join("")}</div><div><span className="status">{c.class}</span><h2>{c.name}</h2><p>{c.email} · {c.phone} · {c.city}</p></div><div className="score"><b>{c.score}</b><small>CLIENT SCORE</small></div></div><div className="metrics"><Metric label="EVENTOS" value={c.events}/><Metric label="TOTAL GASTO" value={money(c.spent)}/><Metric label="TICKET MÉDIO" value={money(c.ticket)}/><Metric label="INGRESSOS" value={c.qty}/><Metric label="EARLY BUYER" value={`${Math.round(c.early/Math.max(1,c.sales.length)*100)}%`}/></div><article className="panel"><div className="sectionHead"><h2>Histórico de compras</h2><button className="danger" onClick={()=>onDelete(c.id)}>Excluir cliente</button></div>{[...c.sales].reverse().map((s:Sale)=><div className="timeline" key={s.id}><i/><span><b>{events.find(e=>e.id===s.eventId)?.name}</b><small>{dt(s.at)} · {s.qty} ingresso(s)</small></span><strong>{money(s.value)}</strong></div>)}</article></>;return <><div className="pageIntro"><h2>{title}</h2><p>{rows.length} clientes encontrados. Clique em qualquer pessoa para abrir o perfil completo.</p></div>{rows.length?<div className="dataTable"><div className="trow thead"><span>CLIENTE</span><span>EVENTOS</span><span>EARLY</span><span>GASTO</span><span>SCORE</span></div>{rows.map(c=><button className="trow" key={c.id} onClick={()=>onDetail(c.id)}><span><b>{c.name}</b><small>{c.email}</small></span><span>{c.events}</span><span>{c.early}</span><span>{money(c.spent)}</span><span><i className="scorePill">{c.score}</i></span></button>)}</div>:<div className="empty"><b>Nenhum cliente encontrado</b><p>Limpe a busca ou altere o segmento.</p></div>}</>}
function Intelligence({data,stats,event}:{data:Store;stats:any[];event:Event}){const missing=stats.filter(c=>c.events>=2&&!c.sales.some((s:Sale)=>s.eventId===event.id));return <><div className="pageIntro"><h2>Insights que pedem ação.</h2><p>Todos os sinais abaixo são calculados a partir da base atual.</p></div><div className="insightGrid"><article><i>01</i><b>{missing.filter(c=>c.score>=71).length} clientes VIP ainda não compraram {event.label}.</b><p>Lista prioritária para ativação comercial.</p></article><article><i>02</i><b>{stats.filter(c=>c.early>=2&&!c.sales.some((s:Sale)=>s.eventId===event.id)).length} early buyers recorrentes estão ausentes.</b><p>O melhor momento de contato é agora.</p></article><article><i>03</i><b>Quinta, entre 18h e 22h, concentra o pico de compras.</b><p>Baseado no horário das vendas registradas.</p></article><article><i>04</i><b>OBOÉ e GINGA compartilham {affinity(data,"OBOÉ","GINGA")}% do público.</b><p>Alta afinidade para campanhas cruzadas.</p></article></div><article className="panel"><h3>Afinidade entre eventos</h3><div className="matrix"><span/><b>OBOÉ</b><b>GINGA</b><b>RETRONEJO</b>{["OBOÉ","GINGA","RETRONEJO"].flatMap(a=>[<b key={a}>{a}</b>,...["OBOÉ","GINGA","RETRONEJO"].map(b=><i key={a+b}>{a===b?100:affinity(data,a,b)}%</i>)] )}</div></article></>}
function affinity(data:Store,a:string,b:string){const ea=data.events.filter(e=>e.label===a).map(e=>e.id),eb=data.events.filter(e=>e.label===b).map(e=>e.id),ca=new Set(data.sales.filter(s=>ea.includes(s.eventId)).map(s=>s.clientId)),cb=new Set(data.sales.filter(s=>eb.includes(s.eventId)).map(s=>s.clientId));return Math.round([...ca].filter(x=>cb.has(x)).length/Math.max(1,ca.size)*100)}
function Mailing({segment,setSegment,count,exportList}:{segment:string;setSegment:(x:string)=>void;count:number;exportList:(x:"csv"|"xls")=>void}){return <><div className="pageIntro"><h2>Crie uma lista pronta para converter.</h2><p>Combine o segmento com a busca global e exporte o mailing.</p></div><article className="builder"><label>SEGMENTO<select value={segment} onChange={e=>setSegment(e.target.value)}>{["Todos","VIP","Early Buyers","Ainda não comprou","Adormecidos"].map(x=><option key={x}>{x}</option>)}</select></label><div className="result"><small>RESULTADO</small><b>{count}</b><span>clientes qualificados</span></div><div><button className="cta" onClick={()=>exportList("csv")}>Exportar CSV</button><button onClick={()=>exportList("xls")}>Exportar XLSX</button></div></article></>}
function Import({onPick,loading}:{onPick:()=>void;loading:boolean}){return <><div className="pageIntro"><h2>Atualize a inteligência da TREND.</h2><p>Importe um CSV. Duplicidades são identificadas por CPF, depois e-mail e telefone.</p></div><button className="dropzone" onClick={onPick}>{loading?<><b>Processando...</b><span>Atualizando clientes e vendas</span></>:<><b>⇧ Escolher mailing CSV</b><span>Campos aceitos: nome, telefone, email, cpf, nascimento, cidade, evento, data, quantidade e valor</span></>}</button></>}
